<a href="https://colab.research.google.com/github/Henil21/Tweet_sentiment_NLP/blob/main/Covid_tweet_Sentiment_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import pandas as pd
# data=pd.read_csv('/content/drive/MyDrive/Dataset/Cov!d.csv',delim_whitespace=True)
!wget https://raw.githubusercontent.com/Henil21/Data_set/main/Corona_NLP_test.csv
! wget https://raw.githubusercontent.com/Henil21/Data_set/main/Corona_NLP_train.csv



--2023-01-09 12:28:02--  https://raw.githubusercontent.com/Henil21/Data_set/main/Corona_NLP_test.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1002494 (979K) [text/plain]
Saving to: ‘Corona_NLP_test.csv’

Corona_NLP_test.csv 100%[===================>] 979.00K  --.-KB/s    in 0.005s  

2023-01-09 12:28:02 (208 MB/s) - ‘Corona_NLP_test.csv’ saved [1002494/1002494]

--2023-01-09 12:28:02--  https://raw.githubusercontent.com/Henil21/Data_set/main/Corona_NLP_train.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10500262 (10M)

In [2]:
import pandas as pd
train=pd.read_csv('Corona_NLP_train.csv',  encoding='latin-1')
# train.head()

test=pd.read_csv("Corona_NLP_test.csv")
test.head()

UserName  ScreenName             Location     TweetAt  \
0         1       44953                  NYC  02-03-2020   
1         2       44954          Seattle, WA  02-03-2020   
2         3       44955                  NaN  02-03-2020   
3         4       44956          Chicagoland  02-03-2020   
4         5       44957  Melbourne, Victoria  03-03-2020   

                                       OriginalTweet           Sentiment  
0  TRENDING: New Yorkers encounter empty supermar...  Extremely Negative  
1  When I couldn't find hand sanitizer at Fred Me...            Positive  
2  Find out how you can protect yourself and love...  Extremely Positive  
3  #Panic buying hits #NewYork City as anxious sh...            Negative  
4  #toiletpaper #dunnypaper #coronavirus #coronav...             Neutral

In [3]:
len(train)

41157

In [4]:
train_dir=train.sample(frac=1,random_state=42)
train_dir.head()

UserName  ScreenName         Location     TweetAt  \
31089     34888       79840            Lagos  06-04-2020   
35564     39363       84315              NaN  09-04-2020   
144        3943       48895              NaN  16-03-2020   
8202      12001       56953  irlande du nord  19-03-2020   
31720     35519       80471   Zaria, Nigeria  07-04-2020   

                                           OriginalTweet           Sentiment  
31089   Without the there would not be any problem wh...             Neutral  
35564  Rice &amp; wheat prices surge amid fears Covid...  Extremely Negative  
144    When the government says to start social dista...            Positive  
8202   What the shops are doing is obeying the law of...            Positive  
31720  Kaduna State Task Force on Covid 19 led by the...            Negative

In [5]:
from sklearn.model_selection import train_test_split
train_tweet,test_tweet,train_sentiment,test_sentiment=train_test_split(train_dir["OriginalTweet"],
                                                                       train_dir["Sentiment"],
                                                                       train_size=0.9,
                                                                       test_size=0.1,
                                                                       random_state=42,
                                                                       shuffle=True)

In [6]:
train_tweet[10:11]

980    “Only after the last can opener broke, Only a...
Name: OriginalTweet, dtype: object

In [7]:
train_sentiment[10:11]

980    Negative
Name: Sentiment, dtype: object

In [8]:
# finding output sequence length
round(sum([len(i.split()) for i in train_tweet])/len(train_tweet))

30

In [9]:
from tensorflow.keras.layers import TextVectorization
Textvec= TextVectorization(max_tokens=20000,
                           output_mode="int",
                           output_sequence_length=30)

In [10]:
Textvec.adapt(train_tweet)
sample_tweet="covid will get over soon stay safe and healthy"
Textvec([sample_tweet])

<tf.Tensor: shape=(1, 30), dtype=int64, numpy=
array([[ 53,  35,  61, 112, 510, 114, 167,   4, 534,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0]])>

In [11]:
import random
sent=random.choice(train_tweet)
print(f"orignal tweet is \n{sent}")
print(f"\n vectorized tweet is\\n{Textvec(sent)}")


orignal tweet is 




#BeerVirus #DamnBeerVirus #CoronaBeer #coronabeervirus https://t.co/

 vectorized tweet is\n[    1  1314   216   206    18    38   284  2761   206     8   342     9
  1300    96   850   854 14550     1     1 12174     1 11731     0     0
     0     0     0     0     0     0]


In [15]:
from tensorflow.keras import layers
embedding = layers.Embedding(input_dim=20000,#set the input shape
                             output_dim=128,
                             input_length=30)



In [18]:
sample=embedding(Textvec(sent))
sample

<tf.Tensor: shape=(30, 128), dtype=float32, numpy=
array([[-0.0392754 , -0.00834936, -0.04503837, ..., -0.01583718,
        -0.00491703,  0.01317346],
       [-0.00309736,  0.01961497, -0.03224782, ..., -0.01051128,
         0.01127274, -0.03728129],
       [ 0.02207459, -0.02513938,  0.04331693, ...,  0.00355508,
        -0.04667073, -0.04190182],
       ...,
       [ 0.00586043,  0.01317522, -0.04158209, ..., -0.02426938,
         0.00659692, -0.02085487],
       [ 0.00586043,  0.01317522, -0.04158209, ..., -0.02426938,
         0.00659692, -0.02085487],
       [ 0.00586043,  0.01317522, -0.04158209, ..., -0.02426938,
         0.00659692, -0.02085487]], dtype=float32)>